#import '../../../rooms/graphql/fragments/Room.gql'
#import '../fragments/User.gql'

query {
  profile {
    ... User,
    rooms {
      ... on Room {
        id,
        name,
        description
      }
    }
  }
}
